$extends$: configs/config.yaml

env: fep
n_train_iters: 40000
actually_stop_at: 40000
batch_size: 32

trainer: recurrent_distillation_trainer
recurrent_distillation: 1
teacher_depth_multiplier: 2
distillation_weight: 0.5
temperature: 1.0
anchor_all_depths: 1

input_tokenizer:
  vocab_size: 50257
  path: openai-community/gpt2

dataset_args:
  dataset_name:
      - ohsuz/fineweb-edu-2024-10-1M  
      - ohsuz/fineweb-edu-2024-10-from-1M-to-2M 
      # - ohsuz/fineweb-edu-2024-10-from-2M-to-3M 
      # - ohsuz/fineweb-edu-2024-10-from-3M-to-4M 
      # - ohsuz/fineweb-edu-2024-10-from-4M-to-5M 
      # - ohsuz/fineweb-edu-2024-10-from-5M-to-6M
      # - ohsuz/fineweb-edu-2024-10-from-6M-to-7M
      # - ohsuz/fineweb-edu-2024-10-from-7M-to-8M
  subset: ""
  chunk_size: 512 

model: llm
model_args:
  dmodel: 256
  num_layers: 4
  mean_recurrence: 4
  mean_backprop_depth: 2
  dropout: 0.0
  attn_dropout: 0.0
  cross_attn_dropout: 0.0

model_checkpoint:
  save_model: 0
  override_checkpoints: 1
  monitor_quantity: "pretrain#loss@16_loops"
  direction: down
  base_dir: 'checkpoints/'
  delete_previous: True
  total_saves: 10

evaluators:
  - name: recurrent_distillation 
    kind: test
    args:
      display_name: pretrain
      dataset_name: ohsuz/fineweb-edu-2024-10-from-8M-to-9M
